### ISSUE TITLE
minor: typo

### ISSUE THREAD

**Issue by rafaelbeirigo** [dsego/demystifying-fourier#1]
This is awesome!  The interactive examples are very helpful! Thank you for making it available!

Below are some minor typos:

That is, sound waves are not made out of sines as real-**word** phenomena.
[...]
Notice how the resulting magnitude **and** also depends on amplitude of the signal we want to analyze.

**Comment by geoshak** [comment]
Yeah, super cool work man. The graphics gave me instant insight on the mechanics for the FT. Cheers!

**Comment by dsego** [comment]
Thank you! Should be good now.
