### ISSUE TITLE
cos(pi) = -cos(0)

### ISSUE THREAD

**Issue by Nullkraft** [dsego/demystifying-fourier#2]
Hi dsego, I was just going through your wonderful article and ran across a small error.

Under the paragraph "Sine/cosine probes and their negatives" you have cos(-pi/4) == -cos(0). 

That should probably be cos(pi) == -cos(0)?

**Comment by dsego** [comment]
Good catch, absolutely, I was probably thinking of sin(-pi/2), not sure how it became pi/4. Thanks for reporting!
